### ISSUE TITLE
[1.8] Natural spawn of the Killer Rabbit of Caerbannog

### ISSUE THREAD

**Issue by AmauryCarrade** [AmauryCarrade/UHPlugin#56]
The natural spawn is disabled in vanilla Minecraft.

Add an option (default `true`) to make this aggressive kind of rabbit spawn, with a custom probability.

```yaml
gameplay-changes:
    killer-rabbit:
        # Between 0 and 1. Set to 0 to disable the spawn (vanilla behavior).
        spawn-probability: 0.02
```
