### ISSUE TITLE
Dead players can't use /togglechat locking them in team chat, with SpectatorPlus and the block commands option.

### ISSUE THREAD

**Issue by Amunak** [AmauryCarrade/UHPlugin#77]
**Version**: 1.1.3 dev (build 2ca188f7ea)

**To reproduce**:
* When you are alive lock your chat to team chat with /togglechat
* Die
* You are now locked to team chat and SpectatorPlus does not allow you to use /togglechat to get back.

**Suggested fix**: When a player dies, move him back to global chat. The fact that team chat is disabled after death is probably good.

**Comment by AmauryCarrade** [comment]
Thanks, I'll look at this.

**Comment by Amunak** [comment]
That was a quick fix, thanks!

**Comment by AmauryCarrade** [comment]
Implemented, as an option enabled by default.

By the way, in the latest builds of SpectatorPlus, you can edit the configuration (`toggles.yml`) like this too:
```yml
chat:
  spectatorChat: 'true'
  blockCommands:
    enabled: 'true'
    adminBypass: 'true'
    whitelist:
    - /togglechat
    - /g
    - /t
```
