### ISSUE TITLE
Allow spectators.... Or not!

### ISSUE THREAD

**Issue by rogama25** [AmauryCarrade/UHPlugin#91]
Please add an option in the config to kick all players that hasn' t joined before start. And another to don't allow spectators at all.

Also I want to say that if you use the last build and you type /uh, the server says Hi!

**Comment by rogama25** [comment]
Sorry by my English :D

**Comment by AmauryCarrade** [comment]
Hi,
 for the latest builds it's perfectly normal, I'm on a complete rewrite on how I manage my commands, so the commands system is currently broken.

 For the main purpose of this issue, yes, good idea :) . I'll implement that in the future.

**Comment by rogama25** [comment]
Thanks <3 This is a great plugin, by the way :))

**Comment by AmauryCarrade** [comment]
By the way, you can already prevent anyone to spectate in the latest stable version (1.2): in the `config.yml`:
```yaml
death:
    # [...]
    kick:
        do: true  # To kick the dead players...
        time: 30  # ...30 seconds after...
        allow-reconnect: false # ...and to ban them from the game (during this game only, of course).
```
